export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
    CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
    SET_CHAT_INFO: "SET_CHAT_INFO",
    //to post 
    SET_MESSAGES:"SET_MESSAGES",
    SET_SOCKET:"SET_SOCKET",
    //to live web
    ADD_MESSAGES:"ADD_MESSAGES",
    SET_MESSAGE_SEARCH:"SET_MESSAGE_SEARCH"
}